name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # We are still using Node 10 for performance reasons
    # Asciidoctor.js performance are not great on Node > 10  
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    - run: npm ci
    - run: npm t
